app:
  version: '1? - 1.0.0-RELEASE'

spring:
  application:
    name: lotte-2nd-project-back-team1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.166.237:3306/hubflow
#    url: jdbc:mysql://127.0.0.1:3306/hubflow
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username : subinasa231@gmail.com
    password : yrsooezvdnidjttx
    protocol : smtp
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
    default-encoding: UTF-8


jwt:
    issuer: chhak0503@gmail.com
    secret: Tz6W1F4Cl4Yl2GyyRjJ5C4v7KRMCA4z4
file:
  upload:
    path: upload